# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b00bc4f50c071fdeea5e4518c5c443cbfaa05832b1cb2b5d300664454a999e4040038ee638ea8e726fbd8e2afa7151792498ba9e5ca0a5542600ed76052671b

test:
  secret_key_base: 097b155052351c2f628b1120844ee7c8b9ad137b9cddd944022f47f82776987643d369ceae6e4c3c7688ecfb73a69bc4086d2bc14ae54013735e114856cef7b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
